language: php

php:
  # - '5.6'
  - '7.0'
  # - '7.1'

services:
- mysql

before_script:
  - cp .env.example .env
  - mysql -e 'create database librairie;'
  - composer global require "squizlabs/php_codesniffer=*"
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:fresh
  # - cd
  - wget http://static.pdepend.org/php/latest/pdepend.phar
  - chmod 777 pdepend.phar

script:
  # - php phpcs /app --colors
  # - php phpcbf /app
  - php vendor/bin/phpunit --testdox
  - php phpdox.phar
  - php pdepend.phar --summary-xml=summary.xml --jdepend-chart=jdepend.svg --overview-pyramid=pyramid.svg ./app
  - open pyramid.svg

notifications:
  email:
    recipients:
      - johann.creneguy@gmail.com
    on_success: always
    on_failure: always
