language: php

php:
  # - '5.6'
  - '7.0'
  # - '7.1'

sudo: false

before_script:
  - composer install
  - php artisan key:generate
  - php artisan migrate:fresh

script:
  - php vendor/bin/phpunit --testdox

notifications:
  email:
    recipients:
      - johann.creneguy@gmail.com
    on_success: always
    on_failure: always
